### ISSUE TITLE
Restrictions on defining multiple event triggers

### ISSUE THREAD

**Issue by tsurdilo** [cncf/wg-serverless#156]
This is related to pr #153
This issue tackles one particular problem with current specification:

**Restrictions on defining multiple event triggers**

1) Let's first define "event" (as in an event-based architecture)
An event is a fact that present a few distinguishing characteristics:
* Usually immutable
* Has temporal constraints: usually you need to correlate multiple events, specifically temporal 
correlations where events are said to happen at some point in time relative to other events.
* Have managed lifecycle:  due to their immutable nature and the temporal constraints, events usually will only match other events during a limited window of time

If you look at issue https://github.com/cncf/wg-serverless/issues/155 there we show some examples of event expressions inside event states.

As per comments on pr #153 we should **not** allow temporal constraints on events and should only allow boolean expressions that are not concerned with them. This means that the workflow specification will not provide means to define event relationships in regards to time (which is at the core of their definition). 

To put it into perspective, workflow specification could model a use case (as mentioned in comments of the pr):

<hr>
The patient is being monitored for multiple physical information. Each monitoring device produces an event and there are multiple monitoring devices. If any one of the events exceeds some threshold, an alert should be raised.
<hr>

but could not model some more realistic real-world use cases such as:

<hr>
The patient is being monitored for multiple physical information. If a patient is having a Heart Attack, immediately call the doctors. If the patient is having a Mild Fever wait 5 minutes and if the temperature is still high call the nurse
<hr>

Where Heart Attach and Mild Fever events might be deducted from several monitoring events  and using temporal constraints of the events produced.

Event relations such  "after", "before", "coincides", "during", "finishes", "finished by", "includes", "overlaps", etc etc, relationships that actually allow you to solve real-life business problems in event-based architectures are simply said as "not allowed".

This is a big limitations as to what serverless workflows can or cannot do. Inability to tackle orchestrating real-live problems one can say makes this specification useless.

2) Proposed solution: pr #153 : 
* it is not in the scope of serverless workflow spec to be a complex event processing service/engine, but still the capability to make decisions based on event temporal constraints is needed to orchestrate real-live business problems.
* instead of dealing with low-level events which by themselves have no meaning or only allow simple use case (such as first one above) serverless workflow defines to consume high-level or "orchestration events" such as "Heart Attack" or "Mild Fever". 
CEP services or Queue based systems provided by cloud providers would need to be responsible to define the complex temporal event rules and produce their corresponding orchestration events. 
* Unions and Intersections of these orchestration events should be done with control flow logic  rather than string expressions. This allows for a portable implementation of those as well as their visual representation.
For example and "or" relationship using parallel state:

<img width="706" alt="Screen Shot 2020-02-05 at 10 34 11 PM" src="https://user-images.githubusercontent.com/119422/73903671-aaa51b80-4867-11ea-8597-262f782222e9.png">

or "and" with simple transitions:

<img width="720" alt="Screen Shot 2020-02-05 at 10 35 34 PM" src="https://user-images.githubusercontent.com/119422/73903781-f1931100-4867-11ea-91d4-b9e635760fe0.png">

This is implemented and documented with examples in #153.

**Comment by cathyhongzhang** [comment]
I think there are two decisions we need to make here: 
1. Should the workflow spec define complex temporal relationship between the triggering events? Or should we leave these definition outside of the workflow spec, i.e. the user of the workflow should depend on an outside CloudEvents Service Component which handles these complicated event expression, such as "eventB happens within 10 minutes of eventA, and eventC happens 10 min after eventA".  
2. Should the workflow spec define none-temporal relationship, such as union and intersection, between the triggering events or "orchestration events", such as "eventA and event B and eventC ".  Or should we ask the user to specify these unions and Intersections of events with workflow control logic? 

I think a meeting dicsussion is needed to make these important decisions. These are good topics for our weekly meeting which will start next Wednesday.

**Comment by manuelstein** [comment]
I think we should document what has been discussed is to allow multiple events.

The intention of the event expression in an event state was to allow actions based on which combination of events had been received. Regardless the order of events, only a boolean logic as to whether an event has happened within a timeout window should be allowed by the spec.

AFAIU, the consensus is to refine the spec to allow exactly that intention.

In the following, I'll focus on the definition of the timeout window.
According to the explanations, when the workflow enters the event state, a timer would start. 
Currently, each eventaction definition in the eventsActions property of the event state defines its own timeout. In this version, any of the eventactions that actually starts processing (because its expression matches), would need to cancel the state's timer to prevent other eventaction definition from causing a timeout. If no eventaction definition's expression matches, the first timeout would win and fire, which causes the state to timeout. This still creates a problem of conflicting timeouts.

AFAIU #162 moves the timeout from the eventaction definition to the event state. That way, the event state has time until timeout to satisfy any of the eventaction definitions to commence some sequence of actions.

Instead of allowing a string expression, there are also atempts in #162 to realize and/or combination of events happening within the timeout window.

**Comment by tsurdilo** [comment]
Should be resolved via https://github.com/cncf/wg-serverless/pull/162

**Comment by tsurdilo** [comment]
resolved via https://github.com/cncf/wg-serverless/commit/2d0d99258f79f27ab943a48fc299a6eeccde6fe0
