### ISSUE TITLE
[workflow] Defining multiple events in eventsActions expression and state data integrity

### ISSUE THREAD

**Issue by tsurdilo** [cncf/wg-serverless#157]
This is related to pr #153
This issue tackles one particular problem with current specification:

**Defining multiple events in eventsActions expression and state data integrity**

Currently our specification defines that in an Event state the payload of events that are expressed in the event expression and trigger actions is merged with the states data. To visualize: 

<img width="699" alt="Screen Shot 2020-02-05 at 10 45 40 PM" src="https://user-images.githubusercontent.com/119422/73904193-408d7600-4869-11ea-86b7-e0adc3e485b9.png">

where the resulting data after the optional event data filter is merged with the state data. 
When using multiple events lets say A,B,C,D,E merging of each events payload into the state data can create many issues and ultimately compromising workflow orchestration decisions. To still do this, we must define possible non-portable merging strategies via extension for example. 
Also, "eventsActions" definition currently define a single event data filter which is optimal for a single event but not in the case of multiple.

2. Proposed solution: pr #153 : As mentioned in issue https://github.com/cncf/wg-serverless/issues/156:
**Unions and Intersections of  events should be done with control flow logic rather than string expressions. This allows for a portable implementation of those as well as their visual representation**
In addition to that to deal with this particular problem we need to allow only a single orchestration event to be defined per eventsActions definition, for example: 

```json
"events": [
 {
  "name": "Event1",
  "type": "event1Type",
  "source": "event1Source"
 },
{
  "name": "Event2",
  "type": "event2Type",
  "source": "event2Source"
 }
],
"states":[  
  {  
     "name":"Event State",
     "type":"EVENT",
     "eventsActions": [{
         "eventRef": {
            "name": "Event1"
         },
         "actions":[  
            {  
               ...
            }
         ]
     },
{
         "eventRef": {
            "name": "Event2"
         },
         "actions":[  
            {  
               ...
            }
         ]
     }
]
...
  }
]
```
This allows for having to merge a single event payload into state data and use the defined event data filter for it.

**Comment by manuelstein** [comment]
AFAICS, parallelstate and parallel-mode eventactions have the same problem but would solve it with actiondatafilter. Would eventdatafilter for each received event also solve it?

**Comment by manuelstein** [comment]
As of now, there is only a single eventdatafilter in an eventaction definition that would be applied to all events collected, correct? that makes absolutely no sense :) 
IMHO each incoming event would need a separate eventdatafilter to achieve conflict-free merging.

Additionally, an event state may get incoming data from a previous state in case it is transitioned to. Because, IIUC, the behaviour of event state is different when a workflow starts with an event state (in which case the event triggering the workflow is being evaluated in the eventaction expression) or whether a workflow transitions into an event state (in which case the passed input [event] is not evaluated against the expression). So conflict-free data merging can become extra complicated.

Furthermore, if I wanted to loop in order to collect a batch of events, I might need to retain more data from the first occurence than from subsequent events. Or have the last occurence overwrite some of the data of the first occurence (as in latest timestamp) or batch the entire set of events altogether to not loose any of the details.

I'm not sure anymore if an eventdatafilter per referred event would be enough. it would also require some dataOutputPath to decide where to inject the received data. This somehow conflicts with the alternate behaviour of the event state.

**Comment by tsurdilo** [comment]
Will move to new repo
