### ISSUE TITLE
Remove open-events folder from proposals

### ISSUE THREAD

**Issue by markito** [cncf/wg-serverless#50]
Since we just renamed open-events to cloud events should we remove the folder below from the proposals folder to clean up ? 

https://github.com/cncf/wg-serverless/tree/master/proposals/open-events

**Comment by duglin** [comment]
hmmm the "open-CADF-events" folder would be old too then. The README does give some indication of what happened. I'm nervous about just deleting stuff. What if we modified the README so that it more clearly stated that those two projects are under the CloudEvents one now?

e.g. I could add a bullet on the README for each folder with a sentence stating its status.

**Comment by duglin** [comment]
If you have time for a PR, go for it!! thanks.
No real preference from me - as long as its clear to a reader what the state of everything is.

**Comment by duglin** [comment]
@markito did you want to PR this?

**Comment by duglin** [comment]
@markito did you still want to do this one or, if you're swamped, I can take a stab at it... just let me know.

**Comment by markito** [comment]
So sorry Dug about the delay. I've fixed the page and pushed but instead of using my fork I already pushed to the cncf repo, hope that's not a big issue.  Thanks!

**Comment by duglin** [comment]
@markito Yeah, we tend to use PRs instead of pushing directly to the repo just so there's at least one other set of eyes on stuff - but thanks!
Closing...
